[[manager.prepend_keymap]]
on   = [ "F" ]
run  = "plugin --sync max-preview"
desc = "Maximize or restore preview"

[[manager.prepend_keymap]]
on   = [ "?" ]
run  = "filter --smart"
desc = "Filter smart"

[[manager.prepend_keymap]]
on   = [ "f" ]
run  = "plugin --sync hide-preview"
desc = "Hide or restore preview"


