function prepend_path() {
    case ":$PATH:" in
        *:"$1":*)
            ;;
        *)
            export PATH="$1${PATH:+:${PATH}}"
    esac
}

if [ -z "$DOTFILES" ]; then
    export DOTFILES=$HOME/dotfiles
    source $DOTFILES/env.sh
fi

# Spicetify
if [ -d "$HOME/.spicetify" ]; then
    prepend_path "$HOME/.spicetify"
fi

# Personal binaries
if [ -f "$ARTI_HOME/env.sh" ]; then
    source "$ARTI_HOME/env.sh"
fi

if [ -f "$CONFIG/cpp_env" ]; then
    source "$CONFIG/cpp_env"
fi

export FZF_ALT_C_COMMAND=''
export FZF_CTRL_T_COMMAND=''
export FZF_DEFAULT_COMMAND='rg --files'

export RIPGREP_CONFIG_PATH="$HOME/.ripgreprc"

export TERMINAL='xterm-256color'
export COLORTERM=truecolor

export STARSHIP_LOG='error'

export DIRENV_LOG_FORMAT=

export QT_QPA_PLATFORMTHEME='qt5ct'

export GPG_TTY=$(tty)

export EDITOR='nvim'
export VISUAL='nvim'

export PAGER='less'
export MANPAGER='nvim +Man!'

export VIRTUAL_ENV_DISABLE_PROMPT=1
export CPM_SOURCE_CACHE=$HOME/dev/.cpm-cache
